### ISSUE TITLE
Should the receivers container be moved under the augment statement and the leafref renamed?

### ISSUE THREAD

**Issue by mjethanandani** [netconf-wg/https-notif#2]
From Martin - "If we don't have a generic indirection, I would like the current https-notif solution better if it didn't put 'receivers' at the top-level, but instead augmented it into '/sn:subscribers', and renamed it to 'https-receivers'.  Further, the 'receiver-ref' should probably be called 'https-receiver-ref' or something."

**Comment by mjethanandani** [comment]
Considering that the definition of receivers is within the namespace of ietf-https-notif, why does the name have to reflect what kind of receiver it is? Also, it is not like there will be a name conflict by calling it receivers.

**Comment by mjethanandani** [comment]
The reason to not move the receiver container under the augment is so as to allow the leafref to point to multiple receivers. 

Also no comments/objections were received on keeping the node 'receiver' as 'receiver'

**Comment by mbj4668** [comment]
Hi,

[What is the process when we have github issues?  I thought that
github would be used to track them, but discussion would be on the
ML?.  Right now I simply reply to the email I got.  Don't know where
it will end up.]

Mahesh Jethanandani <notifications@github.com> wrote:
> The reason to not move the receiver container under the augment is so
> as to allow the leafref to point to multiple receivers.

I don't understand this reason.

Since this is not a stand-alone model, I think it should augment
/sn:subscriptions.  In some way it doesn't matter what nodes are
called and where they are located, but having descriptive names and
keep related nodes under common subtrees helps the understanding of
models.

> Also no comments/objections were received on keeping the node
> 'receiver' as 'receiver'

You are right that the namespace ensures that there won't be a
conflict, but I think that the node names should be descriptive by
themselves.  The namespace / module name is there to ensure
uniqueness, but the model will be easier to understand and use if the
node names are descriptive.  Note that it is quite common that
implementations use these models to render CLIs as well.

Do you think that the model will be worse if we make the suggested
changes?


/martin
