### ISSUE TITLE
What is the user-id of the entity sending the notification?

### ISSUE THREAD

**Issue by mjethanandani** [netconf-wg/https-notif#3]
When the device generates a notification, NACM needs a user-id to find the access control rules. What is that user-id?

**Comment by mjethanandani** [comment]
There are four options for what the user-id could be:

- The user-id is 'root' or 'system' and thus has all the permissions it needs to read the content and generate a notification.
- The user-id is implicit, i.e. the user that configures the subscription is the user-id used for establishing a session with the receiver.
- The user-id is configured explicitly. The request that configures the subscription also specifies the user-id/credentials to be used by NACM to establish authorization. This implies that whoever supports this draft has to implement NACM.
- The user-id is the same as the user-id used to establish a session with the remote receiver. Also implies implementation of NACM. Are there NACM groupings that can be used for this purpose?

**Comment by schoenw** [comment]
Should it not be the user id of the receiver? A name derived from the certificate of the remote endpoint receiving the notification content? See also RFC 7407.

**Comment by mbj4668** [comment]
Specifically the module "ietf-x509-cert-to-name" in RFC 7407.  This is the solution I prefer.

IMO this does not mandate the usage of NACM.  It merely associates a username with the session.  If the device implements NACM then this username is used.

**Comment by kwatsen** [comment]
Hmmm, that works, and is easy to document.   

Since having an TLS (or HTTP) client extract a username from a certificate is uncommon, would you expect this draft to `use` `x509c2n:cert-to-name`, perhaps by augmenting it into the `tls-params` section?




Separately, I just noticed an issue with the `ietf-[net/rest]conf-server` modules using x509c2n:cert-to-name.

```
         leaf fingerprint {
           type x509c2n:tls-fingerprint;
           mandatory true;
           description
             "Specifies a value with which the fingerprint of the
              full certificate presented by the peer is compared.  If
              the fingerprint of the full certificate presented by the
              peer does not match the fingerprint configured, then the
              entry is skipped, and the search for a match continues.";
```

This definition seems to exclude authenticating client certificates via a trust anchor certificate as, if one can configure a fingerprint, then one could also configure the whole certificate (e.g., `tls-server-parameters/client-authentication/client-certs`), thus obviating the need for `tls-server-parameters/client-authentication/ca-certs`.

I note that  `fingerprint` may be 0 characters in length, which is what netconf/restconf servers wanting to support authenticating clients via a trust anchor will need to do in their configurations.  I'll update the examples in those drafts to include an empty `fingerprint` node.

A better definition (I think) would've been:

```
OLD: full certificate presented by the peer 
NEW: full certificate of the certificate used to authenticate the certificate presented by the peer, which MAY be the peer's end-entity certificate.
```

**Comment by mbj4668** [comment]
> Since having an TLS (or HTTP) client extract a username from a certificate is uncommon, would you expect this draft to `use` `x509c2n:cert-to-name`, perhaps by augmenting it into the `tls-params` section?

Yes (the augment should be in this draft, rather than in the more generic tls draft).

**Comment by mjethanandani** [comment]
But x509c2n:cert-to-name is a grouping.

**Comment by kwatsen** [comment]
Confused, a grouping can be augmented into a tree as well, right?

[7.17.1.  The augment's Substatements](https://tools.ietf.org/html/rfc7950#section-7.17.1)

**Comment by mjethanandani** [comment]
> Since having an TLS (or HTTP) client extract a username from a certificate is uncommon, would you expect this draft to `use` `x509c2n:cert-to-name`, perhaps by augmenting **it** into the `tls-params` section?

I am trying to understand what the "it" is in the above statement.

**Comment by mjethanandani** [comment]
Will be added to -01 version of the draft.
