### ISSUE TITLE
Supporting discovery of receiver capabilities

### ISSUE THREAD

**Issue by mjethanandani** [netconf-wg/https-notif#5]
Should this model support the publisher's discovery of receiver capabilities? If so, what capabilities should be supported?

If it should support discovery, should it be configured or auto-discovered?

**Comment by mjethanandani** [comment]
One of the suggestions from Martin was for the publisher to use HTTP OPTIONS against the receiver and have it return a special body or header to indicate its capabilities, e.g. bundled notifications. Alternatively, it can do a GET to the same URI as the POST, and in return get a sx:structure with the capabilities of the receiver.

**Comment by kwatsen** [comment]
OPTIONS or GET works.

OPTIONS might be better because it is defined, in part, to return the "capabilities of a server" and, in case you're wondering, it is allowed to return a response body.   Here is a writeup on that: http://zacstewart.com/2012/04/14/http-options-method.html

GET might not be right, because it suggests the resource has instance data.  We'd have to declare it to be read-only, so there is no expectation that PUT, DELETE, PATCH working.  Of course, POST of course is working, but not in a RC insert-descendent sort of a way.

**Comment by mjethanandani** [comment]
Capabilities that the draft might consider
- binary encoding
- bundled messages, as defined by draft-ietf-netconf-notification-messages

**Comment by mjethanandani** [comment]
Added in v02 of the draft.
